### ISSUE TITLE
Build files don't work with new hxcpp (3.1.39)

### ISSUE THREAD

**Issue by fserb** [michelkaeser/hx-nanomsg#1]
It seems that the whole hxcpp XML spec changed at some point and this project (as well as its dependency) doesn't build at all.
I tried to fix it but can't make the hxcpp build work at all.
Which hxcpp version are you using to make this work?

**Comment by michelkaeser** [comment]
Hi Fernando

Just validated it still works with 3.1.39 for me and it does (doesn't help you, I know :)).

System:
- Haxe 3.1.3
- HXCPP 3.1.39
- OSX 10.10 (worked well on 10.9 as well)
- also tested on some Linux distributions

Have you ensured the path `/usr/local/lib/libnanomsg.(dylib|so)` is correct for your system before running `haxelib run hxcpp -DHXCPP_M64 build/build_bindings.hxml`?

What error message do you get?

**Comment by fserb** [comment]
so, I'm also on OSX10.10, Haxe 3.1.3, and hxcpp 3.1.39.
`haxelib run hxcpp -DHXCPP_M64 build/build_bindings.hxml` works fine. But if I try to run hxcpp to build either `build.xml` or `build/build_api.hxml` it fails with something like:

```
Uncaught exception - target is missing attribute id
```

Maybe I shouldn't be building those in the first place?

**Comment by michelkaeser** [comment]
Ah OK :) the build.xml in the root directory is an Ant build script and needs to be run with

```
export WORKSPACE=.
ant
```

It will build the bindings file (as you already did manually with the build_bindings.hxml file and the API documentation.

Also make sure you manually (for now) clone the hext-core repository and set its path with

```
haxelib dev hext-core .
```

in the checked out develop branch.

**Comment by fserb** [comment]
Hmm.
I guess the root README needs to be updated. :)

And do I need to build this root script or is building the build_bindings.hxml + setting the dev path on haxelib enough to use the library?

Installing `ant` is fine with homebrew, but it means I also need a JDK, etc. :/

**Comment by michelkaeser** [comment]
Yes, might be worth a note.

Building the bindings is enough. All the ant script does on top of that is install dependencies (hxcpp) and build the API documentation.

Would love to see the project you are using this lib at once it is ready :)
